#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
version: '3'

services:

  # ---------------------
  # RabbitMQ service
  # ---------------------
  rabbitmq:
    #image:                    "rabbitmq:3-management"
    image:                    "rabbitmq:3.8.14-management"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: $GENERIC_USER
      RABBITMQ_DEFAULT_PASS: $GENERIC_PWD
    volumes:
      - ./persistent/rabbitmq:/var/lib/rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    # Health check is mandatory so consumers of service dont start till this us up
    # Otherwise there are crashes
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "alarms"]
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "rabbitmq"

  # ---------------------
  # MySQL service
  #  database (dont use 8)
  # ---------------------
  mysql:
    image:                  "mysql:5.7"
    environment:
      MYSQL_DATABASE:       "hawkbit"
      MYSQL_USER:           "hawkbit"
      # Passwords saved persistently, this is for first boot ONLY (have to update in container after that)
      MYSQL_PASSWORD:       $GENERIC_PWD
      MYSQL_ROOT_PASSWORD:  $GENERIC_PWD
    volumes:
       - ./persistent/mysql:/var/lib/mysql
    restart: always
    # Database doesnt needs to be accessed outside container so comment out
    #ports:
    #  - "3307:3306"
    healthcheck:
        test: ["CMD", "mysql", "--user=root", "--password=$GENERIC_PWD", "--execute", 'SHOW DATABASES;']
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "mysql"

  # ---------------------
  # HawkBit simulator
  # ---------------------
  #hawkbit-simulator:
  #  image:                  "hawkbit/hawkbit-device-simulator:latest"
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    hawkbit:
  #      condition: service_healthy
  #  environment:
  #    - 'HAWKBIT_DEVICE_SIMULATOR_AUTOSTARTS_[0]_TENANT=DEFAULT'
  #    - 'SPRING_RABBITMQ_VIRTUALHOST=/'
  #    - 'SPRING_RABBITMQ_HOST=rabbitmq'
  #    - 'SPRING_RABBITMQ_PORT=5672'
  #    - 'SPRING_RABBITMQ_USERNAME=$GENERIC_USER'
  #    - 'SPRING_RABBITMQ_PASSWORD=$GENERIC_PWD'
  #  restart: always
  #  ports:
  #    - "8083:8083"
  #  labels:
  #    NAME: "hawkbit-simulator"

  # ---------------------
  # HawkBit service
  #  update server
  # ---------------------
  hawkbit:
    #image:                  "hawkbit/hawkbit-update-server:latest-mysql"
    image:                  "hawkbit/hawkbit-update-server:0.3.0M7-mysql"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/hawkbit",
        "spring.rabbitmq.host": "rabbitmq",
        "spring.rabbitmq.username": "$GENERIC_USER",
        "spring.rabbitmq.password": "$GENERIC_PWD",
        "spring.datasource.username": "hawkbit",
        "spring.datasource.password": "$GENERIC_PWD",
        "hawkbit.server.im.users[0].username": "$GENERIC_USER",
        "hawkbit.server.im.users[0].password": "{noop}$GENERIC_PWD",
        "hawkbit.server.im.users[0].firstname": "$GENERIC_USER",
        "hawkbit.server.im.users[0].lastname": "",
        "hawkbit.server.im.users[0].email": "$GENERIC_EMAIL",
        "hawkbit.server.im.users[0].permissions": "ALL"
        }'
      #- 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hawkbit'
      #- 'SPRING_RABBITMQ_HOST=rabbitmq'
      #- 'SPRING_RABBITMQ_USERNAME=guest'
      #- 'SPRING_RABBITMQ_PASSWORD=guest'
      #- 'SPRING_DATASOURCE_USERNAME=hawkbit'
      #- 'SPRING_DATASOURCE_PASSWORD=password'
    volumes:
      - ./persistent/hawkbit/data:/opt/hawkbit/data
      - ./persistent/hawkbit/artifactrepo:/opt/hawkbit/artifactrepo
    restart: always
    ports:
      - "9090:8080"
    healthcheck:
        test: ["CMD", "nc", "-zv", "hawkbit", "8080"]
        interval: 30s
        timeout: 10s
        retries: 5
    labels:
      NAME: "hawkbit"
      
  # ---------------------
  # Adminer service
  #  database admin
  # ---------------------
  adminer:
    image:                    "adminer:4.8.0-standalone"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: "mysql:3306"
    restart: always
    ports:
      - "9091:8080"
    labels:
      NAME: "adminer"

